### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by arsjadoun25** [suraj7076/classattendance#1]
Can you elaborate what is this repo about, as I wanted to add a readme section in this.

**Comment by surajmaity1** [comment]
@arsjadoun25  If you want to modify the readme section, use AlertBook repo and make a good readme file 
GitHub repo link - [AlertBook](https://github.com/surajmaity1/AlertBook)

Actually, I am working AlertBook project and will keep it up to date. So, if you want to contribute, go for the AlertBook repo.

**Comment by arsjadoun25** [comment]
Thanks for clarifying it.
